#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Dotenv\Dotenv;

$dotenv = new Dotenv();
$dotenv->load(__DIR__.'/.env');

$application = new Application();

$application->add(new \Panther\Cli\CreateEntityCommand());
$application->add(new \Panther\Cli\CreateMigrationCommand());
$application->add(new \Panther\Cli\MigrateCommand());
$application->add(new \Panther\Cli\MigrateAllCommand());

$application->run();